# Generated by Django 2.1.7 on 2019-03-24 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('k_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('k_idtype', models.CharField(max_length=3)),
                ('n_name', models.CharField(max_length=50)),
                ('n_lastname', models.CharField(max_length=50)),
                ('o_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orderbill',
            fields=[
                ('k_idorderbill', models.IntegerField(primary_key=True, serialize=False)),
                ('f_dateorderbill', models.DateField()),
                ('n_tokenorderbill', models.CharField(max_length=100)),
                ('n_tokenpayment', models.CharField(blank=True, max_length=200, null=True)),
                ('n_status', models.CharField(max_length=3)),
                ('v_total', models.IntegerField()),
                ('k', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petit.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Orderbilldetail',
            fields=[
                ('k_iddetail', models.IntegerField(primary_key=True, serialize=False)),
                ('q_quantity', models.IntegerField()),
                ('v_subtotal', models.IntegerField()),
                ('k_idorderbill', models.ForeignKey(blank=True, db_column='k_idorderbill', null=True, on_delete=django.db.models.deletion.CASCADE, to='petit.Orderbill')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('k_idproduct', models.IntegerField(primary_key=True, serialize=False)),
                ('n_product', models.CharField(max_length=50)),
                ('n_description', models.CharField(blank=True, max_length=200, null=True)),
                ('v_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='orderbilldetail',
            name='k_idproduct',
            field=models.ForeignKey(blank=True, db_column='k_idproduct', null=True, on_delete=django.db.models.deletion.CASCADE, to='petit.Product'),
        ),
    ]
