# Generated by Django 2.1.7 on 2019-03-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('k_id', models.CharField(max_length=50,
                                          primary_key=True, serialize=False)),
                ('k_idtype', models.CharField(max_length=3)),
                ('n_name', models.CharField(max_length=50)),
                ('n_lastname', models.CharField(max_length=50)),
                ('o_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderbill',
            fields=[
                ('k_idorderbill', models.IntegerField(
                    primary_key=True, serialize=False)),
                ('f_dateorderbill', models.DateField()),
                ('n_tokenorderbill', models.CharField(max_length=100)),
                ('n_tokenpayment', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('n_status', models.CharField(max_length=3)),
                ('v_total', models.IntegerField()),
                ('k_iddetail', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orderbill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderbilldetail',
            fields=[
                ('k_iddetail', models.IntegerField(
                    primary_key=True, serialize=False)),
                ('q_quantity', models.IntegerField()),
                ('v_subtotal', models.IntegerField()),
            ],
            options={
                'db_table': 'orderbilldetail',
                'managed': False,
            },
        ),
    ]
