# Generated by Django 2.1.7 on 2019-03-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petit', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('k_idcommerce', models.IntegerField(primary_key=True, serialize=False)),
                ('n_commerce', models.CharField(max_length=50)),
                ('o_address', models.CharField(blank=True, max_length=200, null=True)),
                ('o_telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'commerce',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('k_idorder', models.IntegerField(primary_key=True, serialize=False)),
                ('f_dateorder', models.DateField()),
                ('n_tokenorder', models.CharField(max_length=100)),
                ('n_tokenpayment', models.CharField(blank=True, max_length=100, null=True)),
                ('n_status', models.CharField(max_length=3)),
                ('v_total', models.IntegerField()),
                ('k_iddetail', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('k_iddetail', models.IntegerField(primary_key=True, serialize=False)),
                ('q_quantity', models.IntegerField()),
                ('v_subtotal', models.IntegerField()),
            ],
            options={
                'db_table': 'orderdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('k_idproduct', models.IntegerField(primary_key=True, serialize=False)),
                ('n_product', models.CharField(max_length=50)),
                ('n_description', models.CharField(blank=True, max_length=200, null=True)),
                ('k_idcommerce', models.IntegerField(blank=True, null=True)),
                ('v_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
